### ISSUE TITLE
SourceList.clear - Losing data grid in Chart view

### ISSUE THREAD

**Issue by houstonhaynes** [JordanMarr/ReactiveElmish.Avalonia#31]
Just an FYI - I'm looking at this for the first time in a while and just noticed that the "Actions" list is getting dropped in the UI. I believe that this is happening on "Reset"

[v2-beta]

https://github.com/JordanMarr/ReactiveElmish.Avalonia/assets/8174976/c78e4c4b-2efb-4f4d-8c9b-4e4e3292df53

**Comment by houstonhaynes** [comment]
To confirm I removed `SourceList.clear` and the issue went away (and the Actions list never clears, which I don't mind)

**Comment by houstonhaynes** [comment]
I tried this - no difference. I'm not sure what might cause the entire UI element to disappear. It's out of my depth.

```fsharp
| Reset ->
            // insert new Series - send the current series length to the newSeries function
            model.Series.[0].Values <- newSeries(Some values.Count)
            model.Actions.Clear() 
            model.Actions.Add({ Description = "Reset Chart"; Timestamp = DateTime.Now })
            { model with IsAutoUpdateChecked = false }
```

**Comment by houstonhaynes** [comment]
OK - last experiment - also the same behavior...

```fsharp
| Reset ->
            // insert new Series - send the current series length to the newSeries function
            model.Series[0].Values <- newSeries(Some values.Count)
            { model with
                // deactivate the AutoUpdate ToggleButton in the UI
                IsAutoUpdateChecked = false 
                Actions = model.Actions |> SourceList.clear |> ignore
                          |> SourceList.create
                          |> SourceList.add  { Description = "Reset Chart"; Timestamp = DateTime.Now } }
                          ```

**Comment by JordanMarr** [comment]
Hmm. Interesting!

**Comment by JordanMarr** [comment]
Removing `SourceList.clear` doesn't fix it for me.

**Comment by JordanMarr** [comment]
## v1.0.0-beta.4
* Removed `SourceList.clear` (it was doing the same thing to the `CounterView`).
* Added a `SourceList.removeAll` that iterates and removes all items
