### ISSUE TITLE
XPlat Web issues again

### ISSUE THREAD

**Issue by JordanMarr** [JordanMarr/ReactiveElmish.Avalonia#32]
The xplat build failed, so I upgraded everything to net8.0 and updated to use the new ReactiveElmish.Avalonia v1.0.0.

It runs again, but now the Web project is back to being stuck at the "powered by Avalonia UI" splash page.

I did notice there is a js console error in the browser:
![image](https://github.com/JordanMarr/ReactiveElmish.Avalonia/assets/1030435/7e52d560-6f5d-443e-8d15-9f2b3cefba1e)

Which leads to this issue:
https://github.com/AvaloniaUI/Avalonia/discussions/11037

So maybe the latest template needs to be re-run to replace some of the js files. 🤷‍♂️

@daz10000 @houstonhaynes

**Comment by houstonhaynes** [comment]
@jamie-rower and I were just batting around strategies for getting the XPlat project into our MiniScaffold instance for our project. I'll pull the latest and play with it a bit.

**Comment by houstonhaynes** [comment]
I think I need to understand better where the main.js update comes into play for your template. I just read that thread and I'm more confused now than when I glanced at your screenshot.

**Comment by houstonhaynes** [comment]
OK - I got the same error with .NET7 on MacOS (had to run dotnet workload install twice to get it to load wasm-tools for some reason)

So I read that thread and I'm actually not sure what to do next. Is there a special place where we're supposed to fetch a main.js in order for it to not have this bug?

**Comment by houstonhaynes** [comment]
So - there *is* a difference in the Avalonia XPlat project path... and it's not small - the main diff is there's an avalonia.js file in there when it's *not* in your project. But there are lots of other diffs too - which I'm not clear on whether they're salient.
![Screenshot 2023-12-09 at 4 09 33 PM](https://github.com/JordanMarr/ReactiveElmish.Avalonia/assets/8174976/446560ba-547d-4380-9f0e-debc78690dd6)

**Comment by houstonhaynes** [comment]
![Screenshot 2023-12-09 at 4 12 59 PM](https://github.com/JordanMarr/ReactiveElmish.Avalonia/assets/8174976/100c57eb-dfa4-4ed0-a1f3-2a81e162c5e7)

**Comment by houstonhaynes** [comment]
So the diff between the project folder and the folder that is generated in the "bin" folder is now my latest head-scratcher...

I wish I had a cleaner way of showing this but on the left is the Avalonia project AppBundle and the right is the generated AppBundle in the bin path.

![Screenshot 2023-12-09 at 4 09 33 PM](https://github.com/JordanMarr/ReactiveElmish.Avalonia/assets/8174976/c78a1216-da7a-4ea0-811b-eeecca10299f)

**Comment by JordanMarr** [comment]
> So I read that thread and I'm actually not sure what to do next. What does `maybe the latest template needs to be re-run to replace some of the js files.` mean?

I’m assuming that the .js files are generated by the Avalonia xplat template. So I’m thinking that the way forward is to update to the latest xplat template, create a new project and then copy over the .js files. 
(or maybe just copy them over from the Avalonia git repo)

**Comment by houstonhaynes** [comment]
It looks like your dep for Avalonia is sourcing from AvaloniaCI and not NuGet. Maybe that's it?

**Comment by daz10000** [comment]
I was battling with this and made some progress - I had partly worked out PR, but then the whole main project went on a tear and I've been busy, so I didn't get around to cleaning it up.  It's not 100% working - I ran into the problem with workloads not installing on my machine.  Looks like this branch

https://github.com/daz10000/Elmish.Avalonia/tree/23/11/MNT-update_web_target

I just pushed the changes - mainly to the AppBundle folder, which are from the new template.  There were some residual issues though.   Somehow it was crashing during startup still.  If I did AwaitTask then RunSynchronously on the main startup task, it cashes.  If I don't, it gets further but the elmish loop never started up.   Also for some reason, having FluentTheme in the applicaton styles broken things, so I just commented that out for now.

**Comment by daz10000** [comment]
Bit the bullet and did the merge - will see if I can it to build and run but the branch is at least up to date with the rest of the project.  Let's see if it even builds..

**Comment by JordanMarr** [comment]
I tried updating bundle files from the latest template, and they did change, but still same problem.
https://github.com/JordanMarr/ReactiveElmish.Avalonia/tree/xplat-update

**Comment by daz10000** [comment]
My branch actually starts up, but I can either get it to render and crash or not render at all.  Installing new sdk - let me see if I can it working

**Comment by houstonhaynes** [comment]
I'm on the xplat-update branch and it runs "clean" (no console errors) but it's also just splashing the Powered by Avalonia screen

**Comment by houstonhaynes** [comment]
Do we need a 'paket' for Avalonia templates? 😸

**Comment by daz10000** [comment]
I have everything pulled into that branch, but the desktop app doesn't run properly - I just get an empty window and it never renders the middle part - it's just transparent.  I'm still stuck on not being able to install the wasm workloads to try the web branch.  Might try a different machine at this point.

**Comment by houstonhaynes** [comment]
Funny how on Mac it hard stops if you're not running with elevated privileges

**Comment by daz10000** [comment]
It does stop on the PC too, brilliantly telling you

`Workload update failed: Value cannot be null. (Parameter 's')`

of course..

Ok, I have web version building, and also just stuck on splash screen... let me see if I can get it a little further.

**Comment by daz10000** [comment]
Ah, edge is actually being helpful and giving me the console output which firefox was withholding for some reason.  Now I can see exactly where startup is failing

![image](https://github.com/JordanMarr/ReactiveElmish.Avalonia/assets/6342645/1a4f3e34-006b-413f-90b7-d62b2560efdf)

**Comment by daz10000** [comment]
Yes specifically, it dies trying to use AppCompositionRoot()

![image](https://github.com/JordanMarr/ReactiveElmish.Avalonia/assets/6342645/48376db9-9119-4efe-b162-fdc00928f83d)

because AppCompositionRoot() assumes a main window where the singlepage application styles (basically everything except the desktop),  needs a single usercontrol at the root.

![image](https://github.com/JordanMarr/ReactiveElmish.Avalonia/assets/6342645/e8b4d084-8b81-4182-ad01-2653ef8dd083)

**Comment by daz10000** [comment]
And partial success..  I had to swap out a usercontrol instead of a window for the main"Window", and then the file service can't be added in because it's looking for a window.  The web version works somewhat.. chart isn't drawing but all the rest of the chart controls work.

Any thoughts on how to harmonize the top level controls?


![image](https://github.com/JordanMarr/ReactiveElmish.Avalonia/assets/6342645/d5799484-40af-4c72-bf6b-b19e268c9717)

![image](https://github.com/JordanMarr/ReactiveElmish.Avalonia/assets/6342645/719c4194-1fc1-4bb0-b6bc-d1797c8be1be)

![image](https://github.com/JordanMarr/ReactiveElmish.Avalonia/assets/6342645/243023b7-a816-4527-a472-2150342fba19)

**Comment by houstonhaynes** [comment]
I don't get what you see in FF *and* there's some odd behavior in the re-load of the page. I get the splash page and no favicon.ico the first time - then on refresh FF *mostly* reloads instantly and shows the favicon and Chrome just janks (and no console output).
![Screenshot 2023-12-09 at 7 42 38 PM](https://github.com/JordanMarr/ReactiveElmish.Avalonia/assets/8174976/bda3b0a4-a424-4fe9-ab5d-674f7e5dea59)

![Screenshot 2023-12-09 at 7 42 56 PM](https://github.com/JordanMarr/ReactiveElmish.Avalonia/assets/8174976/4bf08b86-b560-4d49-ab5e-6d1e80dcb5c7)

**Comment by daz10000** [comment]
It did work for me in Firefox now - it's slower, you might need to refresh cache (I opened it in an incognito window but then the main window also worked).  I did have to fix some other small things - like piping the main program task to ignore rather than runsynchronously.  Changes are all on the updated branch,

![image](https://github.com/JordanMarr/ReactiveElmish.Avalonia/assets/6342645/5e4361b8-c28c-4148-b96b-8f04387c82b1)

**Comment by daz10000** [comment]
still broken
* chart doesn't display.
*  should hide filepicker tab in web version (or work out how to do filepicking but assuming that's a no no for web)
*  I realized there's a whole listbox demo that has quietly dropped out of the wiring, I'll put that back in and update.

**Comment by houstonhaynes** [comment]
And I didn't see any updates on the xplat-update branch

**Comment by daz10000** [comment]
sorry, have been working over [here](https://github.com/daz10000/Elmish.Avalonia/tree/23/11/MNT-update_web_target).  I'll get PR updated shortly.

**Comment by daz10000** [comment]
PR #33 updated.

**Comment by houstonhaynes** [comment]
I'm not seeing any difference - I'll come back to a fresh start in the AM.

**Comment by daz10000** [comment]
I was working on a fork and just submitted a PR to the project.   The changes aren’t in the xplat-update branch.  sorry for any confusion.  Am 12/9/23 um 6:01 PM schrieb Houston Haynes ***@***.***>:﻿
I'm not seeing any difference - I'll come back to a fresh start in the AM.

**Comment by houstonhaynes** [comment]
Just wrapping up for the night.. I followed your PR and rebased on main. I'll come back to my WinOS slab in the AM and give it a fresh look.

**Comment by JordanMarr** [comment]
It works again!  🎉

**Comment by daz10000** [comment]
There is still an issue with the graph in the web client but I’ll look tomorrow.  It works for desktop. Might be some incompatibility in the library.Am 12/9/23 um 9:09 PM schrieb Jordan Marr ***@***.***>:﻿
It works again!  🎉

**Comment by JordanMarr** [comment]
I made a few tweaks:
* Added `SourceList` for smoother updates
* Stubbed out a temp `WebFileService` (not implemented)
* Fixed a few file names

**Comment by houstonhaynes** [comment]
Rainstorm here in the early hours - lots of thunder and lightning 🌧️ ⚡ so I'm up 😸 

I'm on WinOS - latest main - web _does_ run but lingers on the "Powered By Avalonia" screen for a moment longer than I expect. Not a deal-breaker but interesting. Maybe I just haven't run it in a while.

**LiveCharts bar chart doesn't render** in `.Web` but does in `.Desktop`. Haven't tried mobile yet - on device or emulated. I updated to their latest version (2.0.0-rc2) and will scout their repo for late-breaking news, if any.

**Comment by houstonhaynes** [comment]
FYI [LiveCharts 2 Issue - AvaloniaXPlatExample.Web - Bar Chart does not display](https://github.com/beto-rodriguez/LiveCharts2/issues/1397)

**Comment by houstonhaynes** [comment]
Android is not so hot either - API 34 on em or 33 on physical (Galaxy Tab 5) I get a "gray screen" and 

`Process finished with exit code -1.` after a looooooooooong launch window.

**Comment by JordanMarr** [comment]
I'm seeing the same on all fronts. 
TBF, the Android emulator is just SLOW in general. It's exactly the same on my MAUI project -- almost unusably slow.
I found that using a real device is preferable. Although setting up a real iPhone is a pain.

**Comment by JordanMarr** [comment]
Good news: I got Android back to working again -- even the chart seems to render properly!
I forgot that when I last upgraded Avalonia, `Activities.fs` code failed to build because `override _.CustomizeAppBuilder(builder)` didn't exist as a method to override, so I commented it out to fix later.

Looking at it again, I saw that they added a new `AvaloniaMainActivity` base class that takes a generic arg:

```F#
type MainActivity() =
    inherit AvaloniaMainActivity<App>()
```

**Comment by houstonhaynes** [comment]
> Although setting up a real iPhone is a pain.

You said a MOUTHFUL. I had my early sample app running on my iPhone - which I confirmed because it's STILL THERE 😁 

But now, even after setting up a fresh dev cert and doing ALL OF THE THINGS that Rider discussion threads suggest I'm still not getting a successful iOS build. It is extremely frustrating and I have too much work to do to bang my head against that right now. So at *some* point I'm going to come back to face this - but for the time I spent on it my money's on a regression in the latest version of Rider.

**Comment by JordanMarr** [comment]
Yes, it is very frustrating! 
It seems like every time I come back to my Xamarin turned MAUI project after a month or more, the iPhone portion fails to build. It's the most unstable, frustrating mess I've ever seen. Many times, the fix comes in the form a new Visual Studio release. 
So, upgrading VS has become a regular part of my MAUI development. I hate it SO much. It makes me want to never do iOS development again. 

I get the impression that a lot of the issues come from the Apple side, but I don't really know.
